//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchNow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearchNow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EngineDescriptions&gt;
        ///	&lt;Engine&gt;
        ///		&lt;Name&gt;Youtube&lt;/Name&gt;
        ///		&lt;Shortcut&gt;y&lt;/Shortcut&gt;
        ///		&lt;Query&gt;https://www.youtube.com/results?search_query={0}&lt;/Query&gt;
        ///	&lt;/Engine&gt;
        ///	&lt;Engine&gt;
        ///		&lt;Name&gt;Google&lt;/Name&gt;
        ///		&lt;Shortcut&gt;g&lt;/Shortcut&gt;
        ///		&lt;Query&gt;https://www.google.gr/#q={0}&lt;/Query&gt;
        ///	&lt;/Engine&gt;
        ///	&lt;Engine&gt;
        ///		&lt;Name&gt;Windows Explorer&lt;/Name&gt;
        ///		&lt;Shortcut&gt;ws&lt;/Shortcut&gt;
        ///		&lt;Query&gt;search-ms:query={0}&amp;amp;&lt;/Query&gt;
        ///	&lt;/Engine&gt;
        ///	&lt;Engine&gt;
        ///		&lt;Name&gt;Wikipedia&lt;/Name&gt;
        ///		&lt;Shortcut&gt;w&lt;/Shortcut&gt;
        ///		&lt;Query&gt;https://en.wikipedia.org/w/index. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string engines {
            get {
                return ResourceManager.GetString("engines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
